# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68d949b4154b619766583794ca24049a8da7651407002f30b3499d5c131be9fc72d221f4c087358e162117fc80d87169b09e94afbe7157af508b7aa5db5d6f92

test:
  secret_key_base: f19bba21dcc81b83d0c647ce8d495c9135a438130d4bb9205eae3ea94f63894a3198f443222061a6be30d3efab39815e6ea07185704137e8c84cb97dadc7bc76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
